Repository Faekrrr/PoorBook, pull requests merged in 2024-05, with the labels that each got.

#1 docker-compose.yml file normalised to both frontend and backend. Need…
  docker-compose.yml
  poorbook-front/Dockerfile
  poorbook-front/package.json
Labels: enhancement

#2 Docker network both for front & backend
  docker-compose.yml
Labels: enhancement

#3 Done work needed to launch them both via compose
  docker-compose.yml
  poorbook-backend/app.py
  poorbook-backend/routes/taskRoute.py
  poorbook-front/Dockerfile
  poorbook-front/nginx/nginx.conf
  poorbook-front/src/App.css
  poorbook-front/src/components/TasksBox.js
Labels: enhancement

#5 Replaced env loading and added POST /tasks/condition
  docker-compose.yml
  poorbook-backend/common/config.py
  poorbook-backend/models/responses/apiResponse.py
  poorbook-backend/routes/taskRoute.py
Labels: bug, documentation, enhancement

#4 Adjusted backend endpoints to frontend requirements
  .DS_Store
  docker-compose.yml
  poorbook-backend/.DS_Store
  poorbook-backend/app.py
  poorbook-backend/common/config.py
  poorbook-backend/data/eventRepository.py
  poorbook-backend/data/noteRepository.py
  poorbook-backend/data/repository.py
  poorbook-backend/data/taskRepository.py
  poorbook-backend/models/.DS_Store
  poorbook-backend/models/entities/event.py
  poorbook-backend/models/entities/task.py
  poorbook-backend/models/enums/taskStatus.py
  poorbook-backend/models/responses/apiResponse.py
  poorbook-backend/routes/auth/__init__.py
  poorbook-backend/routes/auth/validateApiKey.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: bug, enhancement

#7 Refactor of TasksBox.js, Cleaning the mess in css file and writting d…
  docker-compose.yml
  poorbook-front/src/App.css
  poorbook-front/src/axiosInstance.js
  poorbook-front/src/components/TasksBox.js
Labels: enhancement, cleaning

#8 Adding pages, fat css update
  poorbook-front/package-lock.json
  poorbook-front/package.json
  poorbook-front/src/App.css
  poorbook-front/src/App.js
  poorbook-front/src/components/MainContainer.js
  poorbook-front/src/components/Sidebar.js
  poorbook-front/src/components/TasksBox.js
  poorbook-front/src/components/TasksDoneBox.js
  poorbook-front/src/components/TopBar.js
  poorbook-front/src/pages/EventsPage.js
  poorbook-front/src/pages/LocalizatorPage.js
  poorbook-front/src/pages/TasksPage.js
Labels: enhancement, cleaning, refactor

#9 Tasks adjustment
  poorbook-front/package-lock.json
  poorbook-front/package.json
  poorbook-front/src/App.css
  poorbook-front/src/App.js
  poorbook-front/src/components/MainContainer.js
  poorbook-front/src/components/Sidebar.js
  poorbook-front/src/components/TasksBox.js
  poorbook-front/src/components/TasksDoneBox.js
  poorbook-front/src/components/TopBar.js
  poorbook-front/src/pages/EventsPage.js
  poorbook-front/src/pages/LocalizatorPage.js
  poorbook-front/src/pages/TasksPage.js
Labels: enhancement, cleaning
