Repository Faekrrr/PoorBook, pull requests merged in 2024-06, with the labels that each got.

#10 Replaced app global exception handling
  poorbook-backend/app.py
  poorbook-backend/common/authenticator.py
  poorbook-backend/data/repository.py
  poorbook-backend/data/taskRepository.py
  poorbook-backend/models/exceptions/apiExceptions.py
  poorbook-backend/models/exceptions/invalidApiKeyException.py
  poorbook-backend/models/exceptions/missingApiKeyException.py
  poorbook-backend/models/exceptions/statusAlreadySetException.py
  poorbook-backend/models/handlers/exceptionHandler.py
  poorbook-backend/models/responses/apiResponse.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: enhancement

#12 Added fltering and sorting to tasks and extended swagger docs.
  poorbook-backend/app.py
  poorbook-backend/data/repository.py
  poorbook-backend/data/taskRepository.py
  poorbook-backend/models/app/__init__.py
  poorbook-backend/models/app/getCondition.py
  poorbook-backend/models/enums/sortedBy.py
  poorbook-backend/models/exceptions/apiExceptions.py
  poorbook-backend/routes/taskRoute.py
Labels: enhancement

#13 Added note router
  poorbook-backend/app.py
  poorbook-backend/models/entities/note.py
  poorbook-backend/routes/noteRoute.py
Labels: enhancement

#14 Fixed dependencies and docs for note route.
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: bug

#15 Notes box remake to pastebin
  poorbook-front/src/App.css
  poorbook-front/src/components/EventsBox.js
  poorbook-front/src/components/NotesBox.js
Labels: enhancement

#16 Adjusted notes property to fit frontend
  poorbook-backend/models/entities/note.py
  poorbook-backend/routes/noteRoute.py
Labels: refactor

#17 Adjust event endpoint.
  poorbook-backend/models/entities/event.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: enhancement

#18 Notes to pastebin
  poorbook-front/src/App.css
  poorbook-front/src/components/NotesBox.js
Labels: enhancement, refactor

#19 Updated event model, added event route's endpoints.
  poorbook-backend/app.py
  poorbook-backend/data/eventRepository.py
  poorbook-backend/data/repository.py
  poorbook-backend/models/app/conditionModel.py
  poorbook-backend/models/entities/event.py
  poorbook-backend/models/requests/__init__.py
  poorbook-backend/models/requests/eventsModels.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: enhancement, refactor

#20 Modified event model, added progress endpoints
  poorbook-backend/data/repository.py
  poorbook-backend/models/entities/task.py
  poorbook-backend/routes/taskRoute.py
  poorbook-backend/services/__init__.py
  poorbook-backend/services/taskService.py
Labels: enhancement

#22 Path fixes and refactor.
  poorbook-backend/data/eventRepository.py
  poorbook-backend/data/repository.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: bug, cleaning

#23 Fixed naming and routes models.
  poorbook-backend/app.py
  poorbook-backend/models/entities/event.py
  poorbook-backend/models/entities/note.py
  poorbook-backend/models/entities/task.py
  poorbook-backend/models/requests/eventsModels.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
  poorbook-backend/services/taskService.py
Labels: bug, cleaning

#24 Added untracked file.
  poorbook-backend/models/requests/tasksModels.py
Labels: bug

#25 Removed 404 error when there is no items.
  poorbook-backend/models/entities/event.py
  poorbook-backend/models/exceptions/apiExceptions.py
  poorbook-backend/models/responses/apiResponse.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
  poorbook-backend/services/taskService.py
Labels: bug, cleaning

#29 Fix current issues.
  poorbook-backend/Dockerfile
  poorbook-backend/app.py
  poorbook-backend/data/repository.py
  poorbook-backend/models/entities/event.py
  poorbook-backend/models/entities/note.py
  poorbook-backend/models/entities/task.py
  poorbook-backend/models/responses/apiResponse.py
  poorbook-backend/routes/eventRoute.py
  poorbook-backend/routes/noteRoute.py
  poorbook-backend/routes/taskRoute.py
Labels: enhancement, cleaning

#30 change event conditionad endpoint address
  poorbook-backend/routes/eventRoute.py
Labels: enhancement

#31 Added /items endpoint.
  poorbook-backend/.dockerignore
  poorbook-backend/.gitignore
  poorbook-backend/app.py
  poorbook-backend/common/config.py
  poorbook-backend/data/itemRepository.py
  poorbook-backend/models/entities/item.py
  poorbook-backend/models/requests/itemsModels.py
  poorbook-backend/routes/itemRoute.py
  poorbook-backend/tests/__init__.py
  poorbook-backend/tests/itemRouteTests.py
Labels: enhancement
